variables:
  API_TOKEN: $DEPLOYMENT_TOKEN

  deploy:
    stage: deploy
      image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy:latest
        script:
            - /scripts/deploy.sh
              rules:
                  - if: $CI_COMMIT_BRANCH == "main"